#pragma once
// B-2 codegen - the x86-64 macro-assembler used by the BUILD-TIME stencil
// generator (tools/stencilgen). Not part of the runtime: nothing here runs
// or links into libb2_codegen's execution path except as generated bytes.
//
// WHY THIS FILE EXISTS:
// docs/stencils.md SS5: stencil sources can be "generated opcode templates".
// This emitter is the codegen team's template generator: it emits x86-64
// System V code for one stencil body at a time and RECORDS every patchable
// position as a declared hole (Stencil Rule 3: the archive's hole table is
// built here, at build time - the runtime never guesses where to patch).
//
// DISCIPLINE (docs/codegen_contract.md SS2/SS3):
// - RBP is the activation base; all slot accesses are [rbp + disp32] where
//   disp32 is a HOLE filled at instantiation (plan values / RBC stream).
//   Slot holes carry a DELTA (0 = the 4-byte type tag, 8 = the 8-byte
//   payload) recorded in ArchiveHole::imm; the instantiator adds it.
// - Scratch registers only from the SysV caller-saved set; RBX/R12-R15 are
//   never encoded (SS3 register discipline, honored by construction).
// - Every relocation point goes through a hole() overload with an explicit
//   (kind, source, tag) triple; placeholder bytes are 0x66 (an unfilled
//   hole decodes as an invalid instruction, never a silent wrong one).
// - Local branches (inside one stencil body) use the label mechanism below
//   and are resolved at BUILD time - they are not holes (Stencil Rule 3
//   concerns only what the runtime patches).

#include <cstdint>
#include <vector>

#include "b2/baseline/Stencil.h"
#include "b2/codegen/Archive.h"

namespace b2::codegen {

// --- registers (x86-64 encodings) ------------------------------------------------
//
// Only caller-saved integer registers and xmm0-1 are ever used.
enum class Gpr : std::uint8_t {
  Rax = 0, Rcx = 1, Rdx = 2, Rsi = 6, Rdi = 7,
  R8 = 8, R10 = 10, R11 = 11,
};

// Fixed scratch assignment of the generated bodies (readability names).
inline constexpr Gpr kA{Gpr::Rax};   // primary accumulator
inline constexpr Gpr kB{Gpr::Rcx};   // secondary / shift count / setcc
inline constexpr Gpr kC{Gpr::Rdx};   // tertiary / helper payload
inline constexpr Gpr kT{Gpr::R10};   // divisors, flags
inline constexpr Gpr kHelperAct{Gpr::Rdi};  // helper arg1: activation
inline constexpr Gpr kHelperArg2{Gpr::Rsi}; // helper arg2
inline constexpr Gpr kHelperArg3{Gpr::Rdx}; // helper arg3
inline constexpr Gpr kHelperArg4{Gpr::Rcx}; // helper arg4
inline constexpr Gpr kHelperArg5{Gpr::R8};  // helper arg5

// Slot access deltas: a 16-byte Value = tag @+0, payload @+8.
inline constexpr std::uint32_t kDeltaTag = 0;
inline constexpr std::uint32_t kDeltaPayload = 8;

// --- the emitter --------------------------------------------------------------------

// One recorded hole while emitting a body: the archive hole plus the
// pattern step its value comes from (fusion alignment).
struct EmittedHole {
  ArchiveHole hole;
  std::uint8_t step = 0;
};


class X64 {
public:
  // -- byte primitives --
  void u8(std::uint8_t b) { buf_.push_back(b); }
  void u16(std::uint16_t w) { u8(static_cast<std::uint8_t>(w));
                               u8(static_cast<std::uint8_t>(w >> 8)); }
  void u32(std::uint32_t d) { u16(static_cast<std::uint16_t>(d));
                               u16(static_cast<std::uint16_t>(d >> 16)); }
  void i32(std::int32_t d) { u32(static_cast<std::uint32_t>(d)); }

  [[nodiscard]] std::uint32_t size() const noexcept {
    return static_cast<std::uint32_t>(buf_.size());
  }
  [[nodiscard]] std::vector<std::uint8_t> takeCode() { return std::move(buf_); }
  [[nodiscard]] std::vector<EmittedHole> takeHoles() { return std::move(holes_); }

  // -- local labels (build-time branches inside one body; never holes) --
  [[nodiscard]] int newLabel() {
    labels_.push_back(-1);
    return static_cast<int>(labels_.size()) - 1;
  }
  void bind(int label) { labels_[static_cast<std::size_t>(label)] =
                             static_cast<std::int32_t>(buf_.size()); }
  // Local-branch fixups record the position of the REL32 FIELD (after the
  // opcode bytes), so resolveLocals patches the right bytes with the right
  // displacement (rel = target - (field + 4)).
  void jmpLocal(int label) {
    fixups_.push_back({size() + 1, label, -1});
    u8(0xE9);
    i32(0);
  }
  void jccLocal(int cc, int label) {
    fixups_.push_back({size() + 2, label, cc});
    u8(0x0F);
    u8(0x80 + static_cast<std::uint8_t>(cc));
    i32(0);
  }
  // Resolves all local fixups. Must be called exactly once after emission
  // (stencilgen asserts it); a dangling or duplicate label is a build bug.
  void resolveLocals() {
    for (const Fixup& f : fixups_) {
      const std::int32_t target = labels_[static_cast<std::size_t>(f.label)];
      const std::int32_t rel = target - static_cast<std::int32_t>(f.at + 4);
      patch4(f.at, static_cast<std::uint32_t>(rel));
    }
    fixups_.clear();
  }

  // -- hole recording --
  void hole(PatchKind kind, PatchSource source, HoleTag tag,
            std::uint8_t width, std::uint8_t step = 0,
            std::uint8_t helper = 0, std::uint32_t delta = 0) {
    EmittedHole h;
    h.hole.code_offset = size();
    h.hole.kind = kind;
    h.hole.width = width;
    h.hole.source = source;
    h.hole.tag = tag;
    h.hole.helper_id = helper;
    h.hole.step = step;
    h.hole.imm = delta;
    holes_.push_back(h);
    for (std::uint8_t i = 0; i < width; ++i) {
      u8(kHoleFill); // 0x66: unfilled -> invalid insn, never silent
    }
  }

  // --- modrm helpers ---------------------------------------------------------------

  void modrmRbpDisp(std::uint8_t regBits) {
    u8(0x80 | (regBits << 3) | 0x05); // mod=10, rm=rbp, disp32 follows
  }
  void rex(bool w, std::uint8_t reg = 0xFF, std::uint8_t rm = 0xFF,
           bool x = false) {
    std::uint8_t r = 0x40;
    if (w) r |= 0x08;
    if (reg != 0xFF && reg >= 8) r |= 0x04;
    if (x) r |= 0x02;
    if (rm != 0xFF && rm >= 8) r |= 0x01;
    u8(r);
  }

  // --- integer moves -----------------------------------------------------------------

  // mov r64, [rbp + disp32(hole)+delta]
  void loadSlot(Gpr dst, PatchSource src, std::uint8_t step = 0,
                std::uint32_t delta = kDeltaPayload) {
    rex(true, static_cast<std::uint8_t>(dst));
    u8(0x8B);
    modrmRbpDisp(static_cast<std::uint8_t>(dst) & 7);
    hole(PatchKind::SlotOffset, src, HoleTag::Stream, 4, step, 0, delta);
  }
  // mov r32, [rbp + disp32(hole)+delta]  (tag: Plan for FrameSlot locals,
  // Stream for register operands - the plan value channel vs the stream)
  void loadSlot32(Gpr dst, PatchSource src, std::uint8_t step = 0,
                  std::uint32_t delta = kDeltaPayload,
                  HoleTag tag = HoleTag::Stream) {
    rex(false, static_cast<std::uint8_t>(dst));
    u8(0x8B);
    modrmRbpDisp(static_cast<std::uint8_t>(dst) & 7);
    hole(PatchKind::SlotOffset, src, tag, 4, step, 0, delta);
  }
  // mov [rbp + ...], r64
  void storeSlot(Gpr srcReg, PatchSource src, std::uint8_t step = 0,
                 std::uint32_t delta = kDeltaPayload) {
    rex(true, static_cast<std::uint8_t>(srcReg));
    u8(0x89);
    modrmRbpDisp(static_cast<std::uint8_t>(srcReg) & 7);
    hole(PatchKind::SlotOffset, src, HoleTag::Stream, 4, step, 0, delta);
  }
  // mov dword [rbp + ...], imm32 (constant: type tags)
  void storeImm32Slot(PatchSource src, std::uint32_t imm, std::uint8_t step = 0,
                      std::uint32_t delta = kDeltaTag) {
    u8(0xC7);
    modrmRbpDisp(0);
    hole(PatchKind::SlotOffset, src, HoleTag::Stream, 4, step, 0, delta);
    u32(imm);
  }
  // mov qword [rbp + ...], imm32 sign-extended (constant)
  void storeImm32Slot64(PatchSource src, std::int32_t imm,
                        std::uint8_t step = 0,
                        std::uint32_t delta = kDeltaPayload) {
    rex(true);
    u8(0xC7);
    modrmRbpDisp(0);
    hole(PatchKind::SlotOffset, src, HoleTag::Stream, 4, step, 0, delta);
    i32(imm);
  }
  // mov qword [rbp + ...], imm32-HOLE sign-extended (iconst payload):
  // slot disp is a Stream hole; the immediate is a Plan hole.
  void storeImm32Hole64(PatchSource slotSrc, std::uint8_t slotStep,
                        PatchKind kind, PatchSource immSrc, HoleTag tag,
                        std::uint8_t immStep) {
    rex(true);
    u8(0xC7);
    modrmRbpDisp(0);
    hole(PatchKind::SlotOffset, slotSrc, HoleTag::Stream, 4, slotStep, 0,
         kDeltaPayload);
    hole(kind, immSrc, tag, 4, immStep);
  }
  // mov r64, imm64-HOLE (lconst/dconst payloads)
  void movRaxImm64Hole(PatchKind kind, PatchSource source, HoleTag tag) {
    rex(true);
    u8(0xB8);
    hole(kind, source, tag, 8);
  }
  // mov r64, imm64 (constant). B8+rd encodes the register in the opcode's
  // low bits, so r8-r15 need REX.B (NOT REX.R - a lesson pinned by the
  // differential tests: the wrong bit silently targets a different reg).
  void movRegImm64(Gpr dst, std::uint64_t imm) {
    rex(true, 0xFF, static_cast<std::uint8_t>(dst));
    u8(0xB8 + (static_cast<std::uint8_t>(dst) & 7));
    u32(static_cast<std::uint32_t>(imm));
    u32(static_cast<std::uint32_t>(imm >> 32));
  }
  // mov eax, imm32-HOLE (fconst bits)
  void movEaxImm32Hole(PatchKind kind, PatchSource source, HoleTag tag,
                       std::uint8_t step = 0) {
    u8(0xB8);
    hole(kind, source, tag, 4, step);
  }
  // mov r32, imm32 (constant); REX.B extends B8+rd to r8d-r15d.
  void movRegImm32(Gpr dst, std::uint32_t imm) {
    rex(false, 0xFF, static_cast<std::uint8_t>(dst));
    u8(0xB8 + (static_cast<std::uint8_t>(dst) & 7));
    u32(imm);
  }
  // mov r64, r64
  void movRegReg(Gpr dst, Gpr src) {
    rex(true, static_cast<std::uint8_t>(src), static_cast<std::uint8_t>(dst));
    u8(0x89);
    u8(0xC0 | ((static_cast<std::uint8_t>(src) & 7) << 3) |
       (static_cast<std::uint8_t>(dst) & 7));
  }
  // movsxd r64, r32
  void movsxdReg(Gpr dst, Gpr src) {
    rex(true, static_cast<std::uint8_t>(dst), static_cast<std::uint8_t>(src));
    u8(0x63);
    u8(0xC0 | ((static_cast<std::uint8_t>(dst) & 7) << 3) |
       (static_cast<std::uint8_t>(src) & 7));
  }
  // movsxd r64, dword [rbp + ...]
  void movsxdSlot(Gpr dst, PatchSource src, std::uint8_t step = 0) {
    rex(true, static_cast<std::uint8_t>(dst));
    u8(0x63);
    modrmRbpDisp(static_cast<std::uint8_t>(dst) & 7);
    hole(PatchKind::SlotOffset, src, HoleTag::Stream, 4, step, 0,
         kDeltaPayload);
  }

  // --- ALU -----------------------------------------------------------------------------

  enum class Alu : std::uint8_t { Add, Sub, And, Or, Xor, Cmp };

  // op r64, [rbp + ...]
  void aluSlot(Gpr dst, Alu op, PatchSource src, std::uint8_t step = 0,
               std::uint32_t delta = kDeltaPayload) {
    static constexpr std::uint8_t kOpRm[6] = {0x03, 0x2B, 0x23, 0x0B, 0x33, 0x3B};
    rex(true, static_cast<std::uint8_t>(dst));
    u8(kOpRm[static_cast<std::uint8_t>(op)]);
    modrmRbpDisp(static_cast<std::uint8_t>(dst) & 7);
    hole(PatchKind::SlotOffset, src, HoleTag::Stream, 4, step, 0, delta);
  }
  // op r32, [rbp + ...]
  void aluSlot32(Gpr dst, Alu op, PatchSource src, std::uint8_t step = 0,
                 std::uint32_t delta = kDeltaPayload,
                 HoleTag tag = HoleTag::Stream) {
    static constexpr std::uint8_t kOpRm[6] = {0x03, 0x2B, 0x23, 0x0B, 0x33, 0x3B};
    rex(false, static_cast<std::uint8_t>(dst));
    u8(kOpRm[static_cast<std::uint8_t>(op)]);
    modrmRbpDisp(static_cast<std::uint8_t>(dst) & 7);
    hole(PatchKind::SlotOffset, src, tag, 4, step, 0, delta);
  }
  // op r64, r64
  void aluRegReg(Gpr dst, Alu op, Gpr src) {
    static constexpr std::uint8_t kOpRm[6] = {0x01, 0x29, 0x21, 0x09, 0x31, 0x39};
    rex(true, static_cast<std::uint8_t>(src), static_cast<std::uint8_t>(dst));
    u8(kOpRm[static_cast<std::uint8_t>(op)]);
    u8(0xC0 | ((static_cast<std::uint8_t>(src) & 7) << 3) |
       (static_cast<std::uint8_t>(dst) & 7));
  }
  // op r32, r32
  void aluRegReg32(Gpr dst, Alu op, Gpr src) {
    static constexpr std::uint8_t kOpRm[6] = {0x01, 0x29, 0x21, 0x09, 0x31, 0x39};
    rex(false, static_cast<std::uint8_t>(src), static_cast<std::uint8_t>(dst));
    u8(kOpRm[static_cast<std::uint8_t>(op)]);
    u8(0xC0 | ((static_cast<std::uint8_t>(src) & 7) << 3) |
       (static_cast<std::uint8_t>(dst) & 7));
  }
  // op r64, imm32 sign-extended (constant)
  void aluImm32(Gpr dst, Alu op, std::int32_t imm) {
    static constexpr std::uint8_t kDigit[6] = {0, 5, 4, 1, 6, 7};
    rex(true, static_cast<std::uint8_t>(dst));
    u8(0x81);
    u8(0xC0 | (kDigit[static_cast<std::uint8_t>(op)] << 3) |
       (static_cast<std::uint8_t>(dst) & 7));
    i32(imm);
  }
  // op r32, imm32 (constant)
  void aluImm32_32(Gpr dst, Alu op, std::uint32_t imm) {
    static constexpr std::uint8_t kDigit[6] = {0, 5, 4, 1, 6, 7};
    rex(false, static_cast<std::uint8_t>(dst));
    u8(0x81);
    u8(0xC0 | (kDigit[static_cast<std::uint8_t>(op)] << 3) |
       (static_cast<std::uint8_t>(dst) & 7));
    u32(imm);
  }
  // add eax, imm32-HOLE (iinc delta)
  void addEaxImm32Hole(PatchKind kind, PatchSource source, HoleTag tag,
                       std::uint8_t step = 0) {
    u8(0x81);
    u8(0xC0); // mod=11, reg=/0 (add), rm=eax
    hole(kind, source, tag, 4, step);
  }
  // xor eax, imm32 (constant; fneg sign flip)
  void xorEaxImm32(std::uint32_t imm) {
    u8(0x81);
    u8(0xF0); // mod=11, reg=/6 (xor), rm=eax
    u32(imm);
  }

  // imul r64, [rbp + ...]
  void imulSlot(Gpr dst, PatchSource src, std::uint8_t step = 0) {
    rex(true, static_cast<std::uint8_t>(dst));
    u8(0x0F);
    u8(0xAF);
    modrmRbpDisp(static_cast<std::uint8_t>(dst) & 7);
    hole(PatchKind::SlotOffset, src, HoleTag::Stream, 4, step, 0,
         kDeltaPayload);
  }
  // imul r32, [rbp + ...]
  void imulSlot32(Gpr dst, PatchSource src, std::uint8_t step = 0,
                  HoleTag tag = HoleTag::Stream) {
    rex(false, static_cast<std::uint8_t>(dst));
    u8(0x0F);
    u8(0xAF);
    modrmRbpDisp(static_cast<std::uint8_t>(dst) & 7);
    hole(PatchKind::SlotOffset, src, tag, 4, step, 0,
         kDeltaPayload);
  }
  // neg r32 / r64
  void negReg32(Gpr r) {
    rex(false, static_cast<std::uint8_t>(r));
    u8(0xF7);
    u8(0xD8 | (static_cast<std::uint8_t>(r) & 7));
  }
  void negReg64(Gpr r) {
    rex(true, static_cast<std::uint8_t>(r));
    u8(0xF7);
    u8(0xD8 | (static_cast<std::uint8_t>(r) & 7));
  }
  // test r32, r32
  void testReg32(Gpr a, Gpr b) {
    rex(false, static_cast<std::uint8_t>(a), static_cast<std::uint8_t>(b));
    u8(0x85);
    u8(0xC0 | ((static_cast<std::uint8_t>(a) & 7) << 3) |
       (static_cast<std::uint8_t>(b) & 7));
  }
  // xor r32, r32
  void xorRegReg32(Gpr a, Gpr b) {
    rex(false, static_cast<std::uint8_t>(a), static_cast<std::uint8_t>(b));
    u8(0x31);
    u8(0xC0 | ((static_cast<std::uint8_t>(a) & 7) << 3) |
       (static_cast<std::uint8_t>(b) & 7));
  }

  // --- shifts ---------------------------------------------------------------------------
  enum class Shift : std::uint8_t { Shl, Shr, Sar };
  void shiftByCl(Gpr r, Shift s, bool wide) {
    static constexpr std::uint8_t kDigit[3] = {4, 5, 7};
    rex(wide, static_cast<std::uint8_t>(r));
    u8(0xD3);
    u8(0xC0 | (kDigit[static_cast<std::uint8_t>(s)] << 3) |
       (static_cast<std::uint8_t>(r) & 7));
  }

  // --- division --------------------------------------------------------------------------
  void cqo() { u8(0x48); u8(0x99); }
  void cdq() { u8(0x99); }
  void idivReg32(Gpr r) {
    rex(false, 0xFF, static_cast<std::uint8_t>(r));
    u8(0xF7);
    u8(0xF8 | (static_cast<std::uint8_t>(r) & 7));
  }
  void idivReg64(Gpr r) {
    rex(true, 0xFF, static_cast<std::uint8_t>(r));
    u8(0xF7);
    u8(0xF8 | (static_cast<std::uint8_t>(r) & 7));
  }

  // --- setcc / movzx -----------------------------------------------------------------------
  // cc numbers match the jcc encodings (0..15).
  void setcc(Gpr r, std::uint8_t cc) {
    u8(0x0F);
    u8(0x90 + cc);
    u8(0xC0 | (static_cast<std::uint8_t>(r) & 7));
  }
  // movzx r32, r8 (same-or-lower regs)
  void movzxR32R8(Gpr dst, Gpr src) {
    rex(false, static_cast<std::uint8_t>(dst),
        static_cast<std::uint8_t>(src));
    u8(0x0F);
    u8(0xB6);
    u8(0xC0 | ((static_cast<std::uint8_t>(dst) & 7) << 3) |
       (static_cast<std::uint8_t>(src) & 7));
  }
  enum class Ext : std::uint8_t { Zx8, Zx16, Sx8, Sx16 };
  void extendLoad(Gpr dst, Ext e, PatchSource src, std::uint8_t step = 0) {
    rex(false, static_cast<std::uint8_t>(dst));
    u8(0x0F);
    switch (e) {
      case Ext::Zx8: u8(0xB6); break;
      case Ext::Zx16: u8(0xB7); break;
      case Ext::Sx8: u8(0xBE); break;
      case Ext::Sx16: u8(0xBF); break;
    }
    modrmRbpDisp(static_cast<std::uint8_t>(dst) & 7);
    hole(PatchKind::SlotOffset, src, HoleTag::Stream, 4, step, 0,
         kDeltaPayload);
  }

  // --- control flow ---------------------------------------------------------------------------
  void jmpHole(PatchSource source, HoleTag tag, std::uint8_t step = 0) {
    u8(0xE9);
    hole(PatchKind::BranchRel32, source, tag, 4, step);
  }
  void jccHole(std::uint8_t cc, PatchSource source, HoleTag tag,
               std::uint8_t step = 0) {
    u8(0x0F);
    u8(0x80 + cc);
    hole(PatchKind::BranchRel32, source, tag, 4, step);
  }
  // Helper call: movabs r11, <absolute helper address (8-byte hole)>;
  // call r11. Absolute addressing because the code block is mmap'd far
  // from the binary's text (rel32 cannot reach); r11 is SysV scratch.
  void callHelper(std::uint8_t helperId) {
    u8(0x49); u8(0xBB); // movabs r11, imm64
    hole(PatchKind::AbsTarget64, PatchSource::RuntimeHelper, HoleTag::Helper,
         8, 0, helperId);
    u8(0x41); u8(0xFF); u8(0xD3); // call r11
  }
  void ret() { u8(0xC3); }
  void pushRbp() { u8(0x55); }
  void popRbp() { u8(0x5D); }
  void nop() { u8(0x90); }

  // --- SSE (xmm0/xmm1) -----------------------------------------------------------------------
  enum class Xmm : std::uint8_t { X0 = 0, X1 = 1 };

  void loadValue(Xmm dst, PatchSource src, std::uint8_t step = 0,
                 std::uint32_t delta = kDeltaTag,
                 HoleTag tag = HoleTag::Stream) {
    u8(0x0F);
    u8(0x10);
    modrmRbpDisp(static_cast<std::uint8_t>(dst));
    hole(PatchKind::SlotOffset, src, tag, 4, step, 0, delta);
  }
  void storeValue(Xmm src, PatchSource src2, std::uint8_t step = 0,
                  std::uint32_t delta = kDeltaTag,
                  HoleTag tag = HoleTag::Stream) {
    u8(0x0F);
    u8(0x11);
    modrmRbpDisp(static_cast<std::uint8_t>(src));
    hole(PatchKind::SlotOffset, src2, tag, 4, step, 0, delta);
  }
  // movups [rbp + CONST disp32], xmm (fixed control-block offsets)
  void storeValueToAct(Xmm src, std::uint32_t actOffset) {
    u8(0x0F);
    u8(0x11);
    modrmRbpDisp(static_cast<std::uint8_t>(src));
    u32(actOffset);
  }
  // movups xmm, [rbp + CONST disp32]
  void loadValueFromAct(Xmm dst, std::uint32_t actOffset) {
    u8(0x0F);
    u8(0x10);
    modrmRbpDisp(static_cast<std::uint8_t>(dst));
    u32(actOffset);
  }

  void loadFloat(Xmm dst, PatchSource src, std::uint8_t step = 0) {
    u8(0xF3); u8(0x0F); u8(0x10);
    modrmRbpDisp(static_cast<std::uint8_t>(dst));
    hole(PatchKind::SlotOffset, src, HoleTag::Stream, 4, step, 0,
         kDeltaPayload);
  }
  void storeFloat(Xmm src, PatchSource src2, std::uint8_t step = 0) {
    u8(0xF3); u8(0x0F); u8(0x11);
    modrmRbpDisp(static_cast<std::uint8_t>(src));
    hole(PatchKind::SlotOffset, src2, HoleTag::Stream, 4, step, 0,
         kDeltaPayload);
  }
  void loadDouble(Xmm dst, PatchSource src, std::uint8_t step = 0) {
    u8(0xF2); u8(0x0F); u8(0x10);
    modrmRbpDisp(static_cast<std::uint8_t>(dst));
    hole(PatchKind::SlotOffset, src, HoleTag::Stream, 4, step, 0,
         kDeltaPayload);
  }
  void storeDouble(Xmm src, PatchSource src2, std::uint8_t step = 0) {
    u8(0xF2); u8(0x0F); u8(0x11);
    modrmRbpDisp(static_cast<std::uint8_t>(src));
    hole(PatchKind::SlotOffset, src2, HoleTag::Stream, 4, step, 0,
         kDeltaPayload);
  }
  void movdToXmm(Gpr src) { // movd xmm0, r32
    u8(0x66); u8(0x0F); u8(0x6E);
    u8(0xC0 | (static_cast<std::uint8_t>(src) & 7));
  }
  void movdToXmm1(Gpr src) { // movd xmm1, r32
    u8(0x66); u8(0x0F); u8(0x6E);
    u8(0xC8 | (static_cast<std::uint8_t>(src) & 7));
  }
  enum class SseOp : std::uint8_t { Add, Sub, Mul, Div };
  void sseFloat(Xmm dst, SseOp op, PatchSource src, std::uint8_t step = 0) {
    static constexpr std::uint8_t kOps[4] = {0x58, 0x5C, 0x59, 0x5E};
    u8(0xF3); u8(0x0F);
    u8(kOps[static_cast<std::uint8_t>(op)]);
    modrmRbpDisp(static_cast<std::uint8_t>(dst));
    hole(PatchKind::SlotOffset, src, HoleTag::Stream, 4, step, 0,
         kDeltaPayload);
  }
  void sseDouble(Xmm dst, SseOp op, PatchSource src, std::uint8_t step = 0) {
    static constexpr std::uint8_t kOps[4] = {0x58, 0x5C, 0x59, 0x5E};
    u8(0xF2); u8(0x0F);
    u8(kOps[static_cast<std::uint8_t>(op)]);
    modrmRbpDisp(static_cast<std::uint8_t>(dst));
    hole(PatchKind::SlotOffset, src, HoleTag::Stream, 4, step, 0,
         kDeltaPayload);
  }
  void ucomisFloat(Xmm dst, PatchSource src, std::uint8_t step = 0) {
    u8(0x0F); u8(0x2E);
    modrmRbpDisp(static_cast<std::uint8_t>(dst));
    hole(PatchKind::SlotOffset, src, HoleTag::Stream, 4, step, 0,
         kDeltaPayload);
  }
  void ucomisFloatRR() { // ucomiss xmm0, xmm1
    u8(0x0F); u8(0x2E); u8(0xC1);
  }
  void ucomisSelf(bool isDouble) { // NaN check: compare xmm0 with itself
    if (isDouble) {
      u8(0x66); u8(0x0F); u8(0x2E); u8(0xC0); // ucomisd xmm0, xmm0
    } else {
      u8(0x0F); u8(0x2E); u8(0xC0); // ucomiss xmm0, xmm0
    }
  }
  void ucomisDouble(Xmm dst, PatchSource src, std::uint8_t step = 0) {
    u8(0x66); u8(0x0F); u8(0x2E);
    modrmRbpDisp(static_cast<std::uint8_t>(dst));
    hole(PatchKind::SlotOffset, src, HoleTag::Stream, 4, step, 0,
         kDeltaPayload);
  }
  void cvtsi2ssSlot(PatchSource src, bool from64, std::uint8_t step = 0) {
    u8(0xF3);
    if (from64) { rex(true); }
    u8(0x0F); u8(0x2A);
    modrmRbpDisp(0);
    hole(PatchKind::SlotOffset, src, HoleTag::Stream, 4, step, 0,
         kDeltaPayload);
  }
  void cvtsi2sdSlot(PatchSource src, bool from64, std::uint8_t step = 0) {
    u8(0xF2);
    if (from64) { rex(true); }
    u8(0x0F); u8(0x2A);
    modrmRbpDisp(0);
    hole(PatchKind::SlotOffset, src, HoleTag::Stream, 4, step, 0,
         kDeltaPayload);
  }
  void cvttFloatToI32() { u8(0xF3); u8(0x0F); u8(0x2C); u8(0xC0); }
  void cvttFloatToI64() { u8(0xF3); u8(0x48); u8(0x0F); u8(0x2C); u8(0xC0); }
  void cvttDoubleToI32() { u8(0xF2); u8(0x0F); u8(0x2C); u8(0xC0); }
  void cvttDoubleToI64() { u8(0xF2); u8(0x48); u8(0x0F); u8(0x2C); u8(0xC0); }
  // cvtss2sd xmm0, xmm0 / cvtsd2ss xmm0, xmm0
  void cvtFloatDouble(bool floatToDouble) {
    u8(floatToDouble ? 0xF3 : 0xF2);
    u8(0x0F); u8(0x5A); u8(0xC0);
  }

  // --- helper-call sequence building blocks ------------------------------------------------------
  void passActivation() { u8(0x48); u8(0x89); u8(0xEF); } // mov rdi, rbp
  void arg2Imm32Hole(PatchKind kind, PatchSource source, HoleTag tag,
                     std::uint8_t step = 0, std::uint32_t delta = 0) {
    u8(0xBE);
    hole(kind, source, tag, 4, step, 0, delta);
  }
  void arg3Imm32Hole(PatchKind kind, PatchSource source, HoleTag tag,
                     std::uint8_t step = 0, std::uint32_t delta = 0) {
    u8(0xBA);
    hole(kind, source, tag, 4, step, 0, delta);
  }
  void arg4Imm32Hole(PatchKind kind, PatchSource source, HoleTag tag,
                     std::uint8_t step = 0, std::uint32_t delta = 0) {
    u8(0xB9);
    hole(kind, source, tag, 4, step, 0, delta);
  }
  void arg5Imm32Hole(PatchKind kind, PatchSource source, HoleTag tag,
                     std::uint8_t step = 0, std::uint32_t delta = 0) {
    u8(0x41); u8(0xB8); // mov r8d, imm32 (REX.B)
    hole(kind, source, tag, 4, step, 0, delta);
  }
  void arg5Imm32Const(std::uint32_t imm) {
    u8(0x41); u8(0xB8); u32(imm);
  }
  // mov [rbp + const disp32], eax (32-bit store into the control block)
  void storeEaxToAct(std::uint32_t fieldOffset) {
    u8(0x89); u8(0x85); u32(fieldOffset);
  }
  // mov [rbp + const disp32], edi / esi (thunk stores)
  void storeEdiToAct(std::uint32_t fieldOffset) {
    u8(0x89); u8(0xBD); u32(fieldOffset);
  }
  void storeEsiToAct(std::uint32_t fieldOffset) {
    u8(0x89); u8(0xB5); u32(fieldOffset);
  }
  // mov qword [rbp + const disp32], imm32 sign-extended
  void storeImmToAct64(std::uint32_t fieldOffset, std::int32_t imm) {
    u8(0x48); u8(0xC7); u8(0x85); u32(fieldOffset); i32(imm);
  }

  // placeholder fill byte: unfilled holes decode as invalid instructions
  static constexpr std::uint8_t kHoleFill = 0x66;

private:
  struct Fixup {
    std::uint32_t at;
    int label;
    int cc; // -1 = jmp
  };
  void patch4(std::uint32_t at, std::uint32_t value) {
    buf_[at] = static_cast<std::uint8_t>(value);
    buf_[at + 1] = static_cast<std::uint8_t>(value >> 8);
    buf_[at + 2] = static_cast<std::uint8_t>(value >> 16);
    buf_[at + 3] = static_cast<std::uint8_t>(value >> 24);
  }
  std::vector<std::uint8_t> buf_;
  std::vector<EmittedHole> holes_;
  std::vector<std::int32_t> labels_;
  std::vector<Fixup> fixups_;
};

} // namespace b2::codegen
