// B-2 stencilgen - the build-time stencil generator (docs/stencils.md SS5).
//
// WHY THIS TOOL EXISTS:
// Stencil Rule 1: stencil bodies are immutable build artifacts built by the
// toolchain, never by the runtime. This program links the baseline team's
// manifest (builtinStencilSetV0), emits one machine-code body per stencil
// plus the internal instantiation templates (compiler/codegen/src/
// StencilBodies.cpp), VALIDATES the result (the same validateArchive the
// runtime runs - Stencil Rule 4), and writes:
//   - x86_64_v1.archive : the inspectable binary artifact
//   - ArchiveData.cpp   : the embedded byte array libb2_codegen links
//
// Determinism (Rule 124): identical manifest -> byte-identical outputs;
// the codegen tests regenerate and compare.

#include <cstdint>
#include <cstdio>
#include <fstream>
#include <iterator>
#include <string>
#include <vector>

#include "b2/baseline/StencilSet.h"
#include "b2/codegen/Archive.h"

namespace {

int fail(const std::string& msg) {
  std::fprintf(stderr, "[stencilgen] error: %s\n", msg.c_str());
  return 1;
}

bool writeFile(const std::string& path, const std::string& data) {
  std::ofstream f(path, std::ios::binary);
  if (!f) {
    return false;
  }
  f.write(data.data(), static_cast<std::streamsize>(data.size()));
  return static_cast<bool>(f);
}

std::string hexByte(std::uint8_t v) {
  static const char* kHex = "0123456789abcdef";
  std::string out;
  out += kHex[v >> 4];
  out += kHex[v & 0xF];
  return out;
}

} // namespace

int main(int argc, char** argv) {
  std::string outDir = ".";
  for (int i = 1; i < argc; ++i) {
    const std::string arg = argv[i];
    if (arg == "--out-dir" && i + 1 < argc) {
      outDir = argv[++i];
    } else {
      return fail("unexpected argument: " + arg +
                  "\nusage: stencilgen [--out-dir DIR]");
    }
  }

  const b2::baseline::StencilSet set = b2::baseline::builtinStencilSetV0();
  const b2::codegen::Archive archive = b2::codegen::buildArchive(set);

  // Self-check before writing anything (fail the build, never ship a bad
  // archive - Stencil Rule 4 discipline).
  const b2::codegen::ArchiveCheckResult check =
      b2::codegen::validateArchive(archive, set);
  if (!check.ok) {
    return fail("generated archive failed validation: " + check.error);
  }

  const std::vector<std::uint8_t> bytes =
      b2::codegen::serializeArchive(archive);
  if (bytes.empty()) {
    return fail("serialized archive is empty");
  }

  // The binary artifact (inspectable, diffable).
  if (!writeFile(outDir + "/x86_64_v1.archive",
                 std::string(bytes.begin(), bytes.end()))) {
    return fail("cannot write x86_64_v1.archive");
  }

  // The embedded TU. The byte array is split 16 per line for reviewability;
  // the file is regenerated wholesale every build (no manual edits).
  std::string cpp;
  cpp += "// GENERATED by tools/stencilgen - DO NOT EDIT.\n";
  cpp += "// B-2 stencil archive (x86-64 v1), embedded form. Build-time\n";
  cpp += "// artifact per docs/stencils.md SS5 / Stencil Rule 1.\n";
  cpp += "#include <cstdint>\n#include <span>\n\n";
  cpp += "namespace b2::codegen {\n\n";
  cpp += "namespace {\nconstexpr std::uint8_t kArchiveBytes[] = {\n";
  for (std::size_t i = 0; i < bytes.size(); ++i) {
    if (i % 16 == 0) {
      cpp += "    ";
    }
    cpp += "0x" + hexByte(bytes[i]) + ",";
    if (i % 16 == 15 || i + 1 == bytes.size()) {
      cpp += "\n";
    } else {
      cpp += " ";
    }
  }
  cpp += "};\n} // namespace\n\n";
  cpp += "std::span<const std::uint8_t> embeddedArchiveX86_64Bytes() {\n";
  cpp += "  return std::span<const std::uint8_t>(kArchiveBytes,\n";
  cpp += "                                         sizeof(kArchiveBytes));\n";
  cpp += "}\n\n} // namespace b2::codegen\n";
  if (!writeFile(outDir + "/ArchiveData.cpp", cpp)) {
    return fail("cannot write ArchiveData.cpp");
  }

  std::printf(
      "[stencilgen] archive ok: %zu records (%u manifest + %zu internal), "
      "%zu bytes\n",
      archive.records.size(), archive.header.manifest_count,
      archive.records.size() - archive.header.manifest_count, bytes.size());
  return 0;
}
